server:
  port: 9090

ibm:
  mq:
    queueManager: MTGO
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd

app:
  echo:
    queue:
      name: 'DEV.ECHO'
  calculator:
    queue:
      name: 'DEV.CALCULATOR'