version: '3'
services:
  ibm-mq-playground:
    image: ibmcom/mq:latest
    container_name: ibm-mq-playground
    environment:
      - LICENSE=accept
      - MQ_APP_PASSWORD=passw0rd
      - MQ_QMGR_NAME=MTGO
    ports:
      - 1414:1414
      - 9443:9443
    volumes:
      - ./20
#TODO volume with custom configuration
